apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: pocketbase
spec:
  components:
    - name: pocketbase
      type: webservice
      properties:
        image: ghcr.io/muchobien/pocketbase:latest
        ports:
          - port: 8090
            expose: true
      traits:
      - type: napptive-ingress   
        properties:
          name: nginx-ingress
          port: 8090
          path: /
      - type: storage 
        properties:         
            emptyDir: 
              - name: pockerbase-vol
                mountPath: /path/to/data:/pb_data